// Automatically generated file. Do not edit.
// Generated by build-resource-byte-arrays crate.

#[cfg(feature = "build_resource_byte_arrays")]
pub static ARRAY1: &[u8] = include_bytes!("/tmp/123/ARRAY1.bin");

#[cfg(not(feature = "build_resource_byte_arrays"))]
pub static ARRAY1: &[u8] = &[];
